spring:
  application:
    name: cloudServer
server:
  port: 8081
#  servlet:
#    context-path: /server
#  tomcat:
#    uri-encoding: UTF-8
#management:
#  endpoints:
#    web:
#      exposure:
#        include: env, beans, info, configprops, metrics, health, shutdown
#  endpoint:
#    shutdown:
#      enabled: true

#info.app.name: cloudServer
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5

  server:
    enable-self-preservation: false



