spring:
  application:
    name: cloud-feign-api
server:
  port: 8096
  servlet:
    context-path: /gateway
  tomcat:
    uri-encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: env, beans, info, configprops, metrics, health, shutdown
  endpoint:
    shutdown:
      enabled: true

info.app.name: cloud-feign-api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka, http://peer1:8084/eureka, http://peer2:8084/eureka
hystrix:
  metrics:
    polling-interval-ms: 2000

