spring:
  application:
    name: cloudProducer
server:
  port: 8091
  servlet:
    context-path: /producer
  tomcat:
    uri-encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: env, beans, info, configprops, metrics, health, shutdown
  endpoint:
    shutdown:
      enabled: true

info.app.name: cloudProducer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka, http://peer1:8082/eureka, http://peer2:8084/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
