spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: file://E://GitHub/cloud-demo
          search-paths: cloud-config/src/main/resources
      uri: http://localhost:8000
server:
  port: 8000




