spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
#          uri: file://E://GitHub/cloud-demo
          uri: https://github.com/PerPlayer/cloud-demo.git
          search-paths: cloud-config/src/main/resources
      uri: http://www.gateway.cc:8000
server:
  port: 8000


eureka:
  client:
    service-url:
      defaultZone: http://www.gateway.cc:8081/eureka




