spring:
  application:
    name: cloud-zuul
server:
  port: 80
  servlet:
    context-path: /
info.app.name: cloud-zuul

zuul:
  routes:
    config:
      path: /config/**
      url: http://www.gateway.cc:8000
    consumer:
      path: /consumer/**
      url: cloud-consumer
    producer:
      path: /producer/**
      url: cloud-producer
    server:
      path: /server/**
      url: http://www.gateway.cc:8081/
    eureka:
      path: /eureka/**
      url: http://www.gateway.cc:8081/eureka/

eureka:
  client:
    service-url:
      defaultZone: http://www.gateway.cc:8081//eureka

#传统多实例配置
#zuul:
#  routes:
#    consumer:
#      path: /consumer/**
#      url: CLOUDCONSUMER
#ribbon:
#  eureka:
#    enabled: false
#CLOUDCONSUMER:
#  ribbon:
#    listOfServers: http://localhost:8080/, http://localhost:8081/
