spring:
  application:
    name: cloud-consumer
server:
  port: 8096
  servlet:
    context-path: /consumer
  tomcat:
    uri-encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: env, beans, info, configprops, metrics, health, shutdown
  endpoint:
    shutdown:
      enabled: true

info.app.name: cloud-consumer
eureka:
  client:
    service-url:
      defaultZone: http://www.gateway.cc/server/eureka
hystrix:
  metrics:
    polling-interval-ms: 2000
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timoutInMillliseconds: 10000

#ribbon:
#  ConnectTimeout: 2000
#  ReadTimeout: 5000
#CLOUDPRODUCER:
#  ribbon:
#    ConnectTimeout: 1000
#    ReadTimeout: 1000
#    OkToRetryOnAllOperations: false
#    MaxAutoRetriesNextServer: 1
#    MaxAutoRetries: 1
#feign:
#  hystrix:
#    enabled: false

