spring:
  application:
    name: cloud-producer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
    username: root
    password: tiger
server:
  port: 8090
  servlet:
    context-path: /producer
  tomcat:
    uri-encoding: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: env, beans, info, configprops, metrics, health, shutdown
  endpoint:
    shutdown:
      enabled: true

info.app.name: cloud-producer
eureka:
  client:
    service-url:
      defaultZone: http://www.gateway.cc/server/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5

pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  helper-dialect: com.github.pagehelper.dialect.helper.MySqlDialect
